--------------------------------------------------------
--  DDL for Table BANKING
--------------------------------------------------------

  CREATE TABLE "PROJECT"."BANKING" 
   (	"BANK_NO" NUMBER, 
	"BANK_NAME" VARCHAR2(50 BYTE), 
	"BANK_ACCOUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------

  CREATE TABLE "PROJECT"."BOARD" 
   (	"SEQ" NUMBER, 
	"SUBJECT" VARCHAR2(255 BYTE), 
	"NAME" VARCHAR2(40 BYTE), 
	"CONTENT" VARCHAR2(4000 BYTE), 
	"REF" NUMBER, 
	"LEV" NUMBER DEFAULT 0, 
	"STEP" NUMBER DEFAULT 0, 
	"PSEQ" NUMBER DEFAULT 0, 
	"REPLY" NUMBER DEFAULT 0, 
	"HIT" NUMBER DEFAULT 0, 
	"LOGTIME" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BOARDQNA
--------------------------------------------------------

  CREATE TABLE "PROJECT"."BOARDQNA" 
   (	"SEQ" NUMBER, 
	"CATEGORY" VARCHAR2(20 BYTE), 
	"SUBJECT" VARCHAR2(255 BYTE), 
	"ID" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(40 BYTE), 
	"CONTENT" VARCHAR2(4000 BYTE), 
	"ANSWER" VARCHAR2(30 BYTE) DEFAULT NULL, 
	"REF" NUMBER, 
	"LEV" NUMBER DEFAULT 0, 
	"STEP" NUMBER DEFAULT 0, 
	"PSEQ" NUMBER DEFAULT 0, 
	"REPLY" NUMBER DEFAULT 0, 
	"LOGTIME" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "PROJECT"."MEMBER" 
   (	"MEMID" VARCHAR2(30 BYTE), 
	"MEMPWD" VARCHAR2(255 BYTE), 
	"MEMNAME" VARCHAR2(30 BYTE), 
	"MEMBIRTH01" VARCHAR2(5 BYTE), 
	"MEMBIRTH02" VARCHAR2(5 BYTE), 
	"MEMBIRTH03" VARCHAR2(5 BYTE), 
	"MEMGENDER" VARCHAR2(3 BYTE), 
	"MEMEMAIL" VARCHAR2(50 BYTE), 
	"MEMEMAIL0" VARCHAR2(3 BYTE), 
	"MEMZIPCODE" VARCHAR2(50 BYTE), 
	"MEMADDR1" VARCHAR2(70 BYTE), 
	"MEMADDR2" VARCHAR2(50 BYTE), 
	"MEMMOBILE01" VARCHAR2(10 BYTE), 
	"MEMMOBILE02" VARCHAR2(10 BYTE), 
	"MEMMOBILE03" VARCHAR2(10 BYTE), 
	"CONTRY" VARCHAR2(20 BYTE), 
	"LOGTIME" DATE, 
	"LASTNAME" VARCHAR2(6 BYTE) DEFAULT null, 
	"FIRSTNAME" VARCHAR2(20 BYTE) DEFAULT null, 
	"PASSPORTNUMBER" VARCHAR2(10 BYTE) DEFAULT null, 
	"PASSPORTSTARTYEAR" VARCHAR2(6 BYTE) DEFAULT null, 
	"PASSPORTSTARTMONTH" VARCHAR2(6 BYTE) DEFAULT null, 
	"PASSPORTSTARTDAY" VARCHAR2(6 BYTE) DEFAULT null, 
	"PASSPORTENDYEAR" VARCHAR2(6 BYTE) DEFAULT null, 
	"PASSPORTENDMONTH" VARCHAR2(6 BYTE) DEFAULT null, 
	"PASSPORTENDDAY" VARCHAR2(6 BYTE) DEFAULT null, 
	"ENABLED" NUMBER(1,0) DEFAULT '1', 
	"AUTHORITY" VARCHAR2(20 BYTE) DEFAULT 'ROLE_USER'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBERLEAVE
--------------------------------------------------------

  CREATE TABLE "PROJECT"."MEMBERLEAVE" 
   (	"MEMID" VARCHAR2(20 BYTE), 
	"REASON" VARCHAR2(50 BYTE), 
	"REQUIREMENT" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NEWZIPCODE
--------------------------------------------------------

  CREATE TABLE "PROJECT"."NEWZIPCODE" 
   (	"ZIPCODE" VARCHAR2(50 BYTE), 
	"SIDO" VARCHAR2(50 BYTE), 
	"SIGUNGU" VARCHAR2(50 BYTE), 
	"YUBMYUNDONG" VARCHAR2(50 BYTE), 
	"RI" VARCHAR2(50 BYTE), 
	"ROADNAME" VARCHAR2(100 BYTE), 
	"BUILDINGNAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PACKAGES
--------------------------------------------------------

  CREATE TABLE "PROJECT"."PACKAGES" 
   (	"PACK_NO" NUMBER, 
	"PACK_TITLE" VARCHAR2(100 BYTE), 
	"PACK_PRICE_KID" NUMBER, 
	"PACK_PRICE_ADULT" NUMBER, 
	"PACK_DESC" CLOB, 
	"PACK_CITY" VARCHAR2(300 BYTE), 
	"PACK_DEPART" VARCHAR2(30 BYTE), 
	"PACK_ARRIV" VARCHAR2(30 BYTE), 
	"PACK_AIR" VARCHAR2(100 BYTE), 
	"PACK_DETAIL" CLOB, 
	"TOUR_INFO" CLOB, 
	"TOUR_REF" CLOB, 
	"PURCHASE_CNT" NUMBER DEFAULT 0, 
	"IMAGE1" VARCHAR2(300 BYTE), 
	"IMAGE2" VARCHAR2(300 BYTE), 
	"IMAGE3" VARCHAR2(300 BYTE), 
	"IMAGE4" VARCHAR2(300 BYTE), 
	"IMAGE5" VARCHAR2(300 BYTE), 
	"IMAGE6" VARCHAR2(300 BYTE), 
	"IMAGE7" VARCHAR2(300 BYTE), 
	"IMAGE8" VARCHAR2(300 BYTE), 
	"IMAGE9" VARCHAR2(300 BYTE), 
	"PACK_CATEGORY" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("PACK_DESC") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("PACK_DETAIL") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("TOUR_INFO") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("TOUR_REF") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table RESERVELIST
--------------------------------------------------------

  CREATE TABLE "PROJECT"."RESERVELIST" 
   (	"PACK_NO" NUMBER, 
	"MEMID" VARCHAR2(50 BYTE), 
	"RESERVETIME" DATE, 
	"PAYMETHOD" VARCHAR2(50 BYTE), 
	"TOTALPAY" VARCHAR2(100 BYTE), 
	"PAYMENTSTATE" VARCHAR2(50 BYTE), 
	"REVIEWSEQ" NUMBER DEFAULT NULL, 
	"NUMOFPERSON" VARCHAR2(50 BYTE), 
	"LIST_SEQ" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SAFEINFO
--------------------------------------------------------

  CREATE TABLE "PROJECT"."SAFEINFO" 
   (	"SAFEINFO" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("SAFEINFO") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table SCHEDULES
--------------------------------------------------------

  CREATE TABLE "PROJECT"."SCHEDULES" 
   (	"PACK_NO" NUMBER, 
	"SCHEDULES_DATE" VARCHAR2(20 BYTE), 
	"SCHEDULES_NO" NUMBER, 
	"SCHEDULES_CONTENT" VARCHAR2(3000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRAVELREVIEW
--------------------------------------------------------

  CREATE TABLE "PROJECT"."TRAVELREVIEW" 
   (	"SEQ" NUMBER, 
	"ID" VARCHAR2(30 BYTE), 
	"SUBJECT" VARCHAR2(200 BYTE), 
	"CONTENT" VARCHAR2(2000 BYTE), 
	"REVIEWDATE" DATE DEFAULT NULL, 
	"STARSCORE" NUMBER(5,0), 
	"PACK_NO" NUMBER(10,0), 
	"PACK_CITY" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007064
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."SYS_C007064" ON "PROJECT"."MEMBER" ("MEMID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PACK_NO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."PACK_NO_PK" ON "PROJECT"."PACKAGES" ("PACK_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RESERVELIST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."RESERVELIST_PK" ON "PROJECT"."RESERVELIST" ("LIST_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRAVELREVIEW_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."TRAVELREVIEW_PK" ON "PROJECT"."TRAVELREVIEW" ("SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "PROJECT"."BOARD" MODIFY ("REPLY" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."BOARD" MODIFY ("PSEQ" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."BOARD" MODIFY ("STEP" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."BOARD" MODIFY ("LEV" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."BOARD" MODIFY ("REF" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."BOARD" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."BOARD" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."BOARD" MODIFY ("SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."BOARD" MODIFY ("SEQ" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOARDQNA
--------------------------------------------------------

  ALTER TABLE "PROJECT"."BOARDQNA" MODIFY ("REPLY" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."BOARDQNA" MODIFY ("PSEQ" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."BOARDQNA" MODIFY ("STEP" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."BOARDQNA" MODIFY ("LEV" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."BOARDQNA" MODIFY ("REF" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."BOARDQNA" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."BOARDQNA" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."BOARDQNA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."BOARDQNA" MODIFY ("SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."BOARDQNA" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."BOARDQNA" MODIFY ("SEQ" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "PROJECT"."MEMBER" MODIFY ("AUTHORITY" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."MEMBER" MODIFY ("ENABLED" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."MEMBER" ADD PRIMARY KEY ("MEMID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PROJECT"."MEMBER" MODIFY ("MEMMOBILE03" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."MEMBER" MODIFY ("MEMMOBILE02" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."MEMBER" MODIFY ("MEMMOBILE01" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."MEMBER" MODIFY ("MEMADDR2" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."MEMBER" MODIFY ("MEMADDR1" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."MEMBER" MODIFY ("MEMZIPCODE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."MEMBER" MODIFY ("MEMEMAIL" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."MEMBER" MODIFY ("MEMGENDER" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."MEMBER" MODIFY ("MEMBIRTH03" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."MEMBER" MODIFY ("MEMBIRTH02" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."MEMBER" MODIFY ("MEMBIRTH01" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."MEMBER" MODIFY ("MEMNAME" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."MEMBER" MODIFY ("MEMPWD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PACKAGES
--------------------------------------------------------

  ALTER TABLE "PROJECT"."PACKAGES" ADD CONSTRAINT "PACK_NO_PK" PRIMARY KEY ("PACK_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESERVELIST
--------------------------------------------------------

  ALTER TABLE "PROJECT"."RESERVELIST" ADD CONSTRAINT "RESERVELIST_PK" PRIMARY KEY ("LIST_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PROJECT"."RESERVELIST" MODIFY ("LIST_SEQ" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRAVELREVIEW
--------------------------------------------------------

  ALTER TABLE "PROJECT"."TRAVELREVIEW" ADD CONSTRAINT "TRAVELREVIEW_PK" PRIMARY KEY ("SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PROJECT"."TRAVELREVIEW" MODIFY ("SEQ" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TRAVELREVIEW" MODIFY ("PACK_CITY" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TRAVELREVIEW" MODIFY ("PACK_NO" NOT NULL ENABLE);
